<a href="https://colab.research.google.com/github/cibelerusso/FundamentosemCienciasdeDados/blob/main/Notebooks/Fundamentos_em_Ci%C3%AAncias_de_Dados_Aula_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamentos em Ciências de Dados

## Profa. Cibele Russo


### Aula 4: Fatiamento (slicing), loc e iloc no pandas.

### Conteúdo
1. O que é fatiamento?
2. Régua visual de índices
3. Fatiamento básico
4. Fatiamento com omissões
5. Passo (`step`)
6. Índices negativos
7. Inversão com `[::-1]`
8. Fatiamento com strings
9. Fatiamento com listas
10. Cópia com fatiamento
11. Erros comuns
12. Exemplos
13. Fatiamento em matrizes
14. loc e iloc (pandas).

## 1. O que é fatiamento?

**Fatiamento** (ou **slicing**) é uma forma de extrair uma parte específica de uma sequência em Python.

Funciona com:

- listas
- strings
- tuplas
- DataFrames (mas aqui usaremos loc e iloc)

A sintaxe geral é:

```python
sequencia[inicio:fim:passo]
```

Onde:

- `inicio`: índice inicial (**inclui** esse índice)
- `fim`: índice final (**não inclui** esse índice)
- `passo`: de quantos em quantos elementos avançar

## 2. Régua visual de índices

Vamos usar a sequência abaixo:

In [1]:
letras = ['p', 'y', 't', 'h', 'o', 'n']
print(letras)

['p', 'y', 't', 'h', 'o', 'n']

### Índices positivos

```text
  índice:    0    1    2    3    4    5
           ┌────┬────┬────┬────┬────┬────┐
letras =   │ p  │ y  │ t  │ h  │ o  │ n  │
           └────┴────┴────┴────┴────┴────┘
```

### Índices negativos

```text
  índice:   -6   -5   -4   -3   -2   -1
           ┌────┬────┬────┬────┬────┬────┐
letras =   │ p  │ y  │ t  │ h  │ o  │ n  │
           └────┴────┴────┴────┴────┴────┘
```

## 3. Fatiamento básico

In [ ]:
letras = ['p', 'y', 't', 'h', 'o', 'n']

print("letras[1:4] ->", letras[1:4])
print("letras[:3]  ->", letras[:3])
print("letras[3:]  ->", letras[3:])
print("letras[:]   ->", letras[:])

letras[1:4] -> ['y', 't', 'h']
letras[:3]  -> ['p', 'y', 't']
letras[3:]  -> ['h', 'o', 'n']
letras[:]   -> ['p', 'y', 't', 'h', 'o', 'n']

### Entendendo `letras[1:4]`

```text
  índice:    0    1    2    3    4    5
           ┌────┬────┬────┬────┬────┬────┐
letras =   │ p  │ y  │ t  │ h  │ o  │ n  │
                ↑──────────────↑
               início=1     fim=4 (exclusivo)
```

Resultado:

```python
['y', 't', 'h']
```

## Importante: O índice final não entra

Esse é um dos pontos mais importantes do slicing.

In [ ]:
nums = [10, 20, 30, 40, 50]
print(nums[1:3])

[20, 30]

No exemplo acima:

- começa no índice `1` → valor `20`
- para **antes** do índice `3`

Logo, o resultado é:

```python
[20, 30]
```

## 4. Fatiamento com omissões

Quando você omite partes da expressão, o Python assume valores padrão.

In [ ]:
nums = [10, 20, 30, 40, 50]

print("nums[:3]  ->", nums[:3])
print("nums[2:]  ->", nums[2:])
print("nums[:]   ->", nums[:])

nums[:3]  -> [10, 20, 30]
nums[2:]  -> [30, 40, 50]
nums[:]   -> [10, 20, 30, 40, 50]

Interpretação:

- `nums[:3]` → do começo até antes do índice 3
- `nums[2:]` → do índice 2 até o final
- `nums[:]` → cópia da sequência inteira

## 5. Passo (`step`)

O terceiro valor do slicing controla de quantos em quantos elementos o Python vai avançar.

In [ ]:
nums = [10, 20, 30, 40, 50, 60, 70]

print("nums[::2]  ->", nums[::2])
print("nums[1::2] ->", nums[1::2])
print("nums[::3]  ->", nums[::3])

nums[::2]  -> [10, 30, 50, 70]
nums[1::2] -> [20, 40, 60]
nums[::3]  -> [10, 40, 70]

### Visualizando `nums[::2]`

```text
nums =    [10, 20, 30, 40, 50, 60, 70]
índices =   0   1   2   3   4   5   6
            ↑       ↑       ↑       ↑
               passo = 2
```

## 6. Índices negativos

Índices negativos contam a partir do final da sequência.

In [ ]:
nums = [10, 20, 30, 40, 50]

print("nums[-1]   ->", nums[-1])
print("nums[-3:]  ->", nums[-3:])
print("nums[:-2]  ->", nums[:-2])
print("nums[-4:-1] ->", nums[-4:-1])

nums[-1]   -> 50
nums[-3:]  -> [30, 40, 50]
nums[:-2]  -> [10, 20, 30]
nums[-4:-1] -> [20, 30, 40]

Exemplos:

- `nums[-1]` → último elemento
- `nums[-3:]` → últimos 3 elementos
- `nums[:-2]` → tudo, exceto os 2 últimos

## 7. Inversão com `[::-1]`

Quando usamos passo `-1`, percorremos a sequência de trás para frente.

In [ ]:
texto = "python"
print(texto[::-1])

lista = [1, 2, 3, 4, 5]
print(lista[::-1])

nohtyp
[5, 4, 3, 2, 1]

### Visualização

```text
letras =   │ p  │ y  │ t  │ h  │ o  │ n  │
             ←    ←    ←    ←    ←    ←
                passo = -1
```

## 8. Fatiamento com strings

Strings também são sequências, então o slicing funciona da mesma forma.

In [ ]:
texto = "programacao"

print("texto[:4]   ->", texto[:4])
print("texto[4:8]  ->", texto[4:8])
print("texto[::2]  ->", texto[::2])
print("texto[::-1] ->", texto[::-1])

texto[:4]   -> prog
texto[4:8]  -> rama
texto[::2]  -> pormco
texto[::-1] -> oacamargorp

## 9. Fatiamento com listas

In [ ]:
nomes = ["Ana", "Bruno", "Carla", "Daniel", "Eva", "Fábio"]

print("nomes[:2]   ->", nomes[:2])
print("nomes[2:5]  ->", nomes[2:5])
print("nomes[::2]  ->", nomes[::2])
print("nomes[::-1] ->", nomes[::-1])

nomes[:2]   -> ['Ana', 'Bruno']
nomes[2:5]  -> ['Carla', 'Daniel', 'Eva']
nomes[::2]  -> ['Ana', 'Carla', 'Eva']
nomes[::-1] -> ['Fábio', 'Eva', 'Daniel', 'Carla', 'Bruno', 'Ana']

## 10. Cópia com fatiamento

Uma forma simples de copiar listas é usar `[:]`.

In [ ]:
lista1 = [1, 2, 3]
lista2 = lista1[:]

lista2[0] = 999

print("lista1:", lista1)
print("lista2:", lista2)

lista1: [1, 2, 3]
lista2: [999, 2, 3]

## 11. Erros comuns

In [ ]:
nums = [0, 1, 2, 3, 4, 5]

print("nums[2:2]  ->", nums[2:2])
print("nums[4:2]  ->", nums[4:2])
print("nums[4:2:-1] ->", nums[4:2:-1])

nums[2:2]  -> []
nums[4:2]  -> []
nums[4:2:-1] -> [4, 3]

Observe:

- `nums[2:2]` → lista vazia, porque início e fim são iguais
- `nums[4:2]` → lista vazia, porque o slicing anda para frente por padrão
- `nums[4:2:-1]` → funciona, porque agora o passo é negativo

## 12. Exemplos

In [ ]:
lista = [10, 20, 30, 40, 50, 60, 70, 80]

# a) pegue os 4 primeiros elementos
resposta_a = lista[:4]

# b) pegue os 3 últimos elementos
resposta_b = lista[-3:]

# c) pegue os elementos de índice par
resposta_c = lista[::2]

# d) pegue a lista invertida
resposta_d = lista[::-1]

# e) pegue do índice 2 até o índice 6 (sem incluir o 6)
resposta_e = lista[2:6]

print(resposta_a)
print(resposta_b)
print(resposta_c)
print(resposta_d)
print(resposta_e)

[10, 20, 30, 40]
[60, 70, 80]
[10, 30, 50, 70]
[80, 70, 60, 50, 40, 30, 20, 10]
[30, 40, 50, 60]

## 13. Fatiamento em matrizes

In [2]:
# Matriz como lista de listas
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# Linhas
print("Primeira linha:", matriz[0])
print("Linhas 1 e 2:", matriz[1:3])

# Elementos
print("Elemento [0][1]:", matriz[0][1])

Primeira linha: [1, 2, 3]
Linhas 1 e 2: [[4, 5, 6], [7, 8, 9]]
Elemento [0][1]: 2

In [5]:
# Matriz definida como array do numpy
import numpy as np

mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Linha
print("Primeira linha:", mat[0, :])

# Coluna
print("Segunda coluna:", mat[:, 1])

# Submatriz
print("Submatriz (0:2, 1:3):\n", mat[0:2, 1:3])

# Elemento
print("Elemento [1,2]:", mat[1, 2])

# Step (passo)
print("Colunas de 2 em 2:\n", mat[:, ::2])


# Step (passo)
print("Linhas de 2 em 2:\n", mat[::2, :])

Primeira linha: [1 2 3]
Segunda coluna: [2 5 8]
Submatriz (0:2, 1:3):
 [[2 3]
 [5 6]]
Elemento [1,2]: 6
Colunas de 2 em 2:
 [[1 3]
 [4 6]
 [7 9]]
Linhas de 2 em 2:
 [[1 2 3]
 [7 8 9]]

# 14. `loc` e `iloc` no pandas

Primeiro: `slice` funciona com DataFrames?


Sim. Em pandas, o fatiamento pode ser usado de algumas formas:

- `df[2:5]` → fatia **linhas** por posição
- `df.iloc[2:5, 0:2]` → fatia **linhas e colunas** por posição
- `df.loc['a':'d', 'col1':'col3']` → fatia por **rótulos**

Mas, para evitar ambiguidades e deixar o código mais claro, o mais recomendado é usar:

- **`iloc`** para posições numéricas
- **`loc`** para rótulos

In [7]:
import pandas as pd
import numpy as np


### Criando um DataFrame de exemplo

In [8]:
df = pd.DataFrame({
    "nome": ["Ana", "Bruno", "Carla", "Diego", "Eva", "Fábio"],
    "idade": [21, 25, 19, 30, 28, 24],
    "curso": ["Estatística", "Computação", "Matemática", "Estatística", "Física", "Computação"],
    "nota": [8.5, 7.2, 9.1, 6.8, 8.0, 7.9]
})

df

    nome  idade        curso  nota
0    Ana     21  Estatística   8.5
1  Bruno     25   Computação   7.2
2  Carla     19   Matemática   9.1
3  Diego     30  Estatística   6.8
4    Eva     28       Física   8.0
5  Fábio     24   Computação   7.9


### Fatiamento simples em DataFrame

Quando fazemos `df[1:4]`, o pandas retorna as linhas nas posições 1, 2 e 3.

Esse tipo de slice funciona, mas ele atua principalmente sobre as **linhas**.

In [9]:
df[1:4]

    nome  idade        curso  nota
1  Bruno     25   Computação   7.2
2  Carla     19   Matemática   9.1
3  Diego     30  Estatística   6.8


### Usando `iloc`

`iloc` significa **integer location**.  
Ele seleciona dados com base em **posições numéricas**.

### Sintaxe

```python
df.iloc[linhas, colunas]
```

- o índice inicial entra
- o índice final não entra
- funciona como o slicing do Python

In [ ]:
# primeira linha
df.iloc[0]

nome             Ana
idade             21
curso    Estatística
nota             8.5
Name: 0, dtype: object

In [10]:
# linhas 1 até 3
df.iloc[1:4]

    nome  idade        curso  nota
1  Bruno     25   Computação   7.2
2  Carla     19   Matemática   9.1
3  Diego     30  Estatística   6.8

In [11]:
# linhas 1 até 4 e colunas 0 até 1
df.iloc[1:5, 0:2]

    nome  idade
1  Bruno     25
2  Carla     19
3  Diego     30
4    Eva     28

In [12]:
# todas as linhas e apenas a coluna de índice 3
df.iloc[:, 3]

0    8.5
1    7.2
2    9.1
3    6.8
4    8.0
5    7.9
Name: nota, dtype: float64

In [ ]:
# linhas específicas e colunas específicas
df.iloc[[0, 2, 4], [0, 3]]

    nome  nota
0    Ana   8.5
2  Carla   9.1
4    Eva   8.0

### Usando `loc`

`loc` significa **location**.  
Ele seleciona dados com base em **rótulos**.

Para facilitar, vamos criar um novo DataFrame com índices nomeados.

In [13]:

df2 = df.copy()
df2.index = ["a", "b", "c", "d", "e", "f"]
df2

    nome  idade        curso  nota
a    Ana     21  Estatística   8.5
b  Bruno     25   Computação   7.2
c  Carla     19   Matemática   9.1
d  Diego     30  Estatística   6.8
e    Eva     28       Física   8.0
f  Fábio     24   Computação   7.9


### Sintaxe

```python
df.loc[linhas, colunas]
```

Em `loc`, o comportamento do fatiamento por rótulo tem uma diferença importante:

> o limite final costuma ser incluído.

In [14]:
df2

    nome  idade        curso  nota
a    Ana     21  Estatística   8.5
b  Bruno     25   Computação   7.2
c  Carla     19   Matemática   9.1
d  Diego     30  Estatística   6.8
e    Eva     28       Física   8.0
f  Fábio     24   Computação   7.9

In [15]:

# linha de rótulo 'b'
df2.loc["b"]

nome          Bruno
idade            25
curso    Computação
nota            7.2
Name: b, dtype: object

In [ ]:

# linhas de 'b' até 'd' (inclui 'd')
df2.loc["b":"d"]

    nome  idade        curso  nota
b  Bruno     25   Computação   7.2
c  Carla     19   Matemática   9.1
d  Diego     30  Estatística   6.8

In [ ]:
# linhas de 'b' até 'e' e colunas de 'nome' até 'curso'
df2.loc["b":"e", "nome":"curso"]

    nome  idade        curso
b  Bruno     25   Computação
c  Carla     19   Matemática
d  Diego     30  Estatística
e    Eva     28       Física

In [ ]:

# selecionando linhas e colunas específicas
df2.loc[["a", "c", "f"], ["nome", "nota"]]

    nome  nota
a    Ana   8.5
c  Carla   9.1
f  Fábio   7.9


### Diferença principal entre `iloc` e `loc`

#### `iloc`
- usa **posição numérica**
- o fim do slice é **exclusivo**

#### `loc`
- usa **rótulos**
- em slices por rótulos, o fim costuma ser **inclusivo**

In [ ]:
print("Com iloc:")
display(df2.iloc[1:4, 0:3])

print("Com loc:")
display(df2.loc["b":"d", "nome":"curso"])

Com iloc:

    nome  idade        curso
b  Bruno     25   Computação
c  Carla     19   Matemática
d  Diego     30  Estatística

Com loc:

    nome  idade        curso
b  Bruno     25   Computação
c  Carla     19   Matemática
d  Diego     30  Estatística


### Filtrando com condição e usando `loc`

`loc` também é muito útil com condições lógicas.

In [ ]:

df2.loc[df2["nota"] >= 8.0, ["nome", "nota", "curso"]]

    nome  nota        curso
a    Ana   8.5  Estatística
c  Carla   9.1   Matemática
e    Eva   8.0       Física

In [ ]:

df2.loc[(df2["curso"] == "Estatística") & (df2["nota"] >= 7.0)]

  nome  idade        curso  nota
a  Ana     21  Estatística   8.5


### Exemplos com séries temporais

`loc` fica especialmente útil quando o índice é uma data.

In [16]:
datas = pd.date_range("2026-01-01", periods=8, freq="D")

df_datas = pd.DataFrame({
    "vendas": [120, 135, 128, 140, 150, 145, 160, 155],
    "clientes": [30, 34, 29, 38, 41, 37, 45, 43]
}, index=datas)

df_datas

            vendas  clientes
2026-01-01     120        30
2026-01-02     135        34
2026-01-03     128        29
2026-01-04     140        38
2026-01-05     150        41
2026-01-06     145        37
2026-01-07     160        45
2026-01-08     155        43

In [17]:
# fatiamento por posição
df_datas.iloc[2:5]

            vendas  clientes
2026-01-03     128        29
2026-01-04     140        38
2026-01-05     150        41

In [18]:

# fatiamento por datas
df_datas.loc["2026-01-03":"2026-01-06"]

            vendas  clientes
2026-01-03     128        29
2026-01-04     140        38
2026-01-05     150        41
2026-01-06     145        37


### Erros comuns

### Erro 1: misturar posição com rótulo

- `iloc` não aceita nome de coluna
- `loc` não aceita posição numérica quando o índice é textual

### Erro 2: esquecer que `loc` inclui o fim no slice

### Erro 3: usar `df[...]` achando que sempre seleciona linhas e colunas

Para maior clareza, prefira `loc` e `iloc`.

In [ ]:
# Exemplo correto com iloc
df2.iloc[0:3, 0:2]

    nome  idade
a    Ana     21
b  Bruno     25
c  Carla     19

In [ ]:
# Exemplo correto com loc
df2.loc["a":"c", "nome":"curso"]

    nome  idade        curso
a    Ana     21  Estatística
b  Bruno     25   Computação
c  Carla     19   Matemática


###  Resumo

- **slice funciona com DataFrames**
- **`iloc`** usa posições numéricas
- **`loc`** usa rótulos
- em **`iloc`**, o final do slice é excluído
- em **`loc`**, o final do slice por rótulo é incluído
- para código mais legível, prefira `loc` e `iloc`


### Exercícios propostos

1. Selecione as linhas 2 até 4 usando `iloc`.
2. Selecione apenas as colunas `nome` e `nota` usando `loc`.
3. Filtre apenas estudantes com nota maior ou igual a 8.
4. No `df_datas`, selecione os dias de 2026-01-02 até 2026-01-05.
5. Compare o resultado de `df2.iloc[1:3]` com `df2.loc["b":"c"]`.