<a href="https://colab.research.google.com/github/cibelerusso/FundamentosemCienciasdeDados/blob/main/Notebooks/Fundamentos_em_Ci%C3%AAncias_de_Dados_Aula5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Alguns comandos em Numpy para cálculos envolvendo vetores e matrizes e mais sobre Pandas


por **Cibele Russo**

**ICMC/USP - São Carlos SP**

### <font color='blue'><b>Parte 1</font>

- Introdução brevíssima de Python: numpy, pandas

- Subconjuntos lógicos de dados, loc, groupby

<b>Referências:</b>

- Biblioteca numpy: https://numpy.org/

- Biblioteca pandas: https://pandas.pydata.org/

## Parte 1

- Introdução brevíssima de Python: numpy, pandas

- Análise descritiva

### <b>Biblioteca Numpy

Biblioteca para computação científica, com operações com vetores e matrizes e implementação de diversas funções matemáticas

https://numpy.org/

In [ ]:
# Carregando a biblioteca

import numpy as np

In [ ]:
# Definindo vetores

a = np.array([[1],[2],[5]])
b = np.array([[1],[3],[3]])
a, b

(array([[1],
        [2],
        [5]]),
 array([[1],
        [3],
        [3]]))

In [ ]:
# Soma de dois vetores
a+b

array([[2],
       [5],
       [8]])

In [ ]:
# Produto interno b^T.a
c = b.T.dot(a)
c

array([[22]])

In [ ]:
# Matrizes
A = np.array([[7,5,3],[5,6,2],[2,2,8]])
B = np.array([[6,3,3],[12,6,6],[4,5,8]])
A, B

(array([[7, 5, 3],
        [5, 6, 2],
        [2, 2, 8]]),
 array([[ 6,  3,  3],
        [12,  6,  6],
        [ 4,  5,  8]]))

In [ ]:
# Multiplicação por escalar
w = 2
w*A

array([[14, 10,  6],
       [10, 12,  4],
       [ 4,  4, 16]])

In [ ]:
# Produto de duas matrizes
A.dot(B)

array([[114,  66,  75],
       [110,  61,  67],
       [ 68,  58,  82]])

In [ ]:
# Determinante de uma matriz

print(np.linalg.det(A), '\n', np.linalg.det(B))

122.00000000000003
 0.0

In [ ]:
# Dimensão de uma matriz
A.shape

(3, 3)

In [ ]:
# Inversa de uma matriz
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.36065574, -0.27868852, -0.06557377],
       [-0.29508197,  0.40983607,  0.00819672],
       [-0.01639344, -0.03278689,  0.13934426]])

In [ ]:
A_inv.dot(A)

array([[ 1.00000000e+00,  3.05311332e-16,  2.22044605e-16],
       [ 9.02056208e-17,  1.00000000e+00, -1.94289029e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [ ]:
# Conferindo as contas
np.round(A_inv.dot(A))

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0.,  0.,  1.]])

**Exercício**

Calcule a inversa da matriz

$\left[\begin{array}{ccc}1 & 2 & 5 & 8\\ 2 & 2 & 5 & 10\\ 3& 4 & 5 & 10\\ 2& 3 & 6& 10 \end{array}\right]$

In [ ]:
# Resposta:

A = np.array([[1, 2, 5, 8],[2, 2, 5, 10], [3, 4, 5, 10], [2, 3, 6, 10]])
A

array([[ 1,  2,  5,  8],
       [ 2,  2,  5, 10],
       [ 3,  4,  5, 10],
       [ 2,  3,  6, 10]])

In [ ]:
B = np.linalg.inv(A)
B

array([[-3.33333333,  0.33333333, -1.        ,  3.33333333],
       [ 1.66666667, -0.66666667,  1.        , -1.66666667],
       [-1.66666667, -0.33333333, -1.        ,  2.66666667],
       [ 1.16666667,  0.33333333,  0.5       , -1.66666667]])

In [ ]:
np.round(B.dot(A),1)

array([[ 1., -0., -0., -0.],
       [ 0.,  1.,  0.,  0.],
       [-0., -0.,  1., -0.],
       [ 0., -0.,  0.,  1.]])

### <b>Biblioteca Pandas

Pandas é usada para manipulação e análise de dados estruturados, com DataFrames que facilitam limpeza, transformação e agregação de dados.

https://pandas.pydata.org/

## <b>Motivação: Dados de clientes de um banco</b>

Considere uma amostra de 500 clientes de um banco no arquivo amostra_banco_distritos.csv. Estão disponíveis as variáveis:

- Cliente: Identificador do cliente.
- Sexo: Feminino (F) ou Masculino (M)
- Idade: Idade do cliente, em anos completos.
- Empresa: Tipo da empresa em que trabalha: Pública, Privada ou Autônomo
- Salário: Salário declarado pelo cliente na abertura da conta, em reais.
- Saldo_cc: Saldo em conta corrente, em reais.
- Saldo_poupança: Saldo em poupança, em reais.
- Saldo_investimento: Saldo em investimentos, em reais.
- Devedor_cartao: Valor em atraso no cartão de crédito, em reais.
- Inadimplente: Se o cliente é considerado inadimplente atualmente (1) ou não (0), de acordo com critérios preestabelecidos.
- Distrito: Distrito de São Paulo em que mora o cliente.


<b>Faça a leitura dos dados. Desenvolva a exploração e visualização dos dados. Verifique possíveis associações entre variáveis. Visualize dados em um mapa.</b>

In [ ]:
import pandas as pd

# Leitura de dados em csv a partir de um link

url='https://raw.githubusercontent.com/cibelerusso/Datasets/main/amostra_banco_distrito.csv'

dados = pd.read_csv(url, sep=',', decimal=',')
dados.head(20)

,Cliente,Sexo,Idade,Empresa,Salario,Saldo_cc,Saldo_poupança,Saldo_investimento,Devedor_cartao,Inadimplente,Distrito
0,106,F,32,Autônomo,6162.00,-372.36,0.0,0.0,1736.56,1,IPIRANGA
1,310,M,34,Privada,3898.30,-45.74,0.0,0.0,3567.22,1,ITAQUERA
2,431,F,28,Privada,5517.00,-527.95,0.0,0.0,2722.83,1,PENHA
3,590,F,28,Pública,5546.20,907.92,0.0,0.0,114.49,0,VILA PRUDENTE
4,971,F,32,Pública,5276.00,1143.71,0.0,0.0,647.00,0,PENHA
5,1002,F,31,Autônomo,5150.00,-51.75,0.0,0.0,3134.78,1,CAMPO LIMPO
6,1409,M,30,Autônomo,7256.20,792.29,0.0,0.0,1610.88,1,SE
7,1612,F,30,Privada,4963.00,579.65,0.0,0.0,3560.45,0,PERUS
8,1780,M,34,Privada,7278.75,1081.82,0.0,0.0,264.00,0,CASA VERDE-CACHOEIRINHA
9,2145,M,32,Pública,5347.00,43.52,0.0,0.0,2767.24,1,PIRITUBA-JARAGUA
10,2196,F,31,Privada,3901.80,693.35,0.0,0.0,2488.00,1,SAO MATEUS
11,2328,M,34,Privada,6027.00,644.98,0.0,0.0,662.97,0,ERMELINO MATARAZZO
12,2676,M,38,Privada,4378.50,1140.90,0.0,0.0,3907.82,0,ITAQUERA
13,2765,F,30,Privada,3526.90,952.88,0.0,0.0,136.00,0,M'BOI MIRIM
14,2926,M,35,Privada,3991.40,-10.82,0.0,0.0,4137.44,1,CAPELA DO SOCORRO
15,3318,M,38,Privada,6807.90,1212.47,0.0,0.0,46.00,0,LAPA
16,3433,M,32,Privada,6244.70,984.16,0.0,0.0,1441.76,1,VILA PRUDENTE
17,3545,F,32,Pública,5062.00,561.57,0.0,0.0,0.00,0,VILA MARIA-VILA GUILHERME
18,4138,M,30,Pública,5267.00,495.65,0.0,0.0,3674.17,0,CAMPO LIMPO
19,4501,M,35,Privada,4872.80,-32.17,0.0,0.0,274.00,0,CIDADE ADEMAR

In [ ]:
dados

,Cliente,Sexo,Idade,Empresa,Salario,Saldo_cc,Saldo_poupança,Saldo_investimento,Devedor_cartao,Inadimplente,Distrito
0,106,F,32,Autônomo,6162.0,-372.36,0.0,0.0,1736.56,1,IPIRANGA
1,310,M,34,Privada,3898.3,-45.74,0.0,0.0,3567.22,1,ITAQUERA
2,431,F,28,Privada,5517.0,-527.95,0.0,0.0,2722.83,1,PENHA
3,590,F,28,Pública,5546.2,907.92,0.0,0.0,114.49,0,VILA PRUDENTE
4,971,F,32,Pública,5276.0,1143.71,0.0,0.0,647.00,0,PENHA
...,...,...,...,...,...,...,...,...,...,...,...
495,98661,M,31,Privada,5841.0,878.31,0.0,0.0,1588.36,0,ARICANDUVA-FORMOSA-CARRAO
496,99693,F,33,Privada,5523.0,907.84,0.0,0.0,1888.18,0,ARICANDUVA-FORMOSA-CARRAO
497,99951,F,33,Privada,5862.0,1269.47,0.0,0.0,92.00,0,ITAIM PAULISTA
498,99956,F,35,Privada,6218.4,883.14,0.0,0.0,1856.47,0,BUTANTA
499,99985,F,31,Autônomo,4090.8,-70.68,0.0,0.0,4403.00,1,ITAQUERA

In [ ]:
dados[['Empresa', 'Distrito']]

      Empresa                   Distrito
0    Autônomo                   IPIRANGA
1     Privada                   ITAQUERA
2     Privada                      PENHA
3     Pública              VILA PRUDENTE
4     Pública                      PENHA
..        ...                        ...
495   Privada  ARICANDUVA-FORMOSA-CARRAO
496   Privada  ARICANDUVA-FORMOSA-CARRAO
497   Privada             ITAIM PAULISTA
498   Privada                    BUTANTA
499  Autônomo                   ITAQUERA

[500 rows x 2 columns]

In [ ]:
# Listando as categorias de Empresa

pd.unique(dados['Empresa'])

array(['Autônomo', 'Privada', 'Pública'], dtype=object)

In [ ]:
# Ordenando os dados por uma coluna

dados.sort_values(by='Empresa')

,Cliente,Sexo,Idade,Empresa,Salario,Saldo_cc,Saldo_poupança,Saldo_investimento,Devedor_cartao,Inadimplente,Distrito
0,106,F,32,Autônomo,6162.00,-372.36,0.00,0.00,1736.5600,1,IPIRANGA
225,45971,F,27,Autônomo,4888.00,-82.96,0.00,0.00,376.0000,0,ARICANDUVA-FORMOSA-CARRAO
223,45701,M,30,Autônomo,6784.70,-59.43,0.00,0.00,1954.7800,1,IPIRANGA
221,45342,F,26,Autônomo,4582.00,-88.29,13975.72,8428.60,0.0000,0,SANTANA-TUCURUVI
212,43567,F,33,Autônomo,5957.50,350.03,14143.06,9245.37,0.0000,0,MOOCA
...,...,...,...,...,...,...,...,...,...,...,...
389,79990,F,30,Pública,5997.20,834.53,16244.59,12228.74,0.0000,0,VILA PRUDENTE
195,39524,F,30,Pública,4997.00,795.99,0.00,0.00,0.0000,0,CAMPO LIMPO
146,31744,M,34,Pública,6980.00,892.44,17357.12,7758.28,0.0000,0,MOOCA
207,42489,F,29,Pública,3385.85,672.69,0.00,0.00,282.3405,0,M'BOI MIRIM
248,51455,M,33,Pública,5322.00,805.45,0.00,0.00,3480.9700,0,SAPOPEMBA

### Agregação (agrupamento) de dados: groupby

In [ ]:
dados.groupby(by='Distrito').mean(numeric_only=True).sort_values(by='Inadimplente', ascending=False)

,Cliente,Idade,Salario,Saldo_cc,Saldo_poupança,Saldo_investimento,Devedor_cartao,Inadimplente
Distrito,,,,,,,,
GUAIANASES,66566.333333,33.333333,4550.400000,792.953333,0.000000,0.000000,1839.290000,0.500000
PARELHEIROS,50969.333333,30.266667,3711.680000,681.799333,0.000000,0.000000,1443.010000,0.466667
ITAQUERA,42083.346154,32.653846,3899.296154,697.180769,0.000000,0.000000,2944.003846,0.461538
VILA PRUDENTE,43382.818182,31.090909,5893.200000,232.494545,1476.780909,1111.703636,889.233636,0.454545
ERMELINO MATARAZZO,40033.111111,30.888889,5459.666667,459.871111,1832.421111,1040.307778,1709.377778,0.444444
CAPELA DO SOCORRO,49592.368421,32.052632,3871.957895,432.477895,0.000000,0.000000,2180.389474,0.421053
ARICANDUVA-FORMOSA-CARRAO,73427.833333,31.416667,5477.666667,395.705000,0.000000,0.000000,1234.876667,0.416667
CIDADE ADEMAR,45774.583333,33.333333,4628.200000,655.425000,0.000000,0.000000,2720.068333,0.416667
PENHA,48933.550000,31.450000,5490.750000,638.500000,0.000000,0.000000,1927.856500,0.400000
M'BOI MIRIM,46764.095238,32.095238,3743.411905,725.521905,0.000000,0.000000,1879.669548,0.380952
SAO MATEUS,51900.250000,31.450000,3828.370000,521.920500,0.000000,0.000000,1555.744000,0.350000
ITAIM PAULISTA,46333.600000,32.600000,5683.700000,711.321500,0.000000,0.000000,2192.458000,0.350000
SE,48220.857143,31.571429,7476.866667,633.226667,756.222857,605.809524,988.514286,0.333333
PERUS,38854.166667,30.500000,5244.000000,731.075000,0.000000,0.000000,1804.671667,0.333333
SAO MIGUEL,49915.750000,33.062500,4007.893750,821.531875,0.000000,0.000000,1647.735000,0.312500
CAMPO LIMPO,41518.000000,32.130435,5462.652174,691.462609,0.000000,0.000000,2716.144348,0.304348
CASA VERDE-CACHOEIRINHA,48460.882353,32.176471,6900.220588,730.812941,0.000000,0.000000,1960.548235,0.294118
IPIRANGA,51289.761905,32.285714,7077.942857,707.821429,1474.380000,1088.118571,1357.560000,0.285714
CIDADE TIRADENTES,54118.000000,31.571429,4413.942857,553.777143,0.000000,0.000000,2083.540000,0.285714
SAPOPEMBA,58347.312500,33.625000,5792.687500,705.633125,0.000000,0.000000,2528.639375,0.250000
PIRITUBA-JARAGUA,51261.666667,31.523810,5836.857143,709.225714,0.000000,0.000000,1815.450476,0.238095
VILA MARIA-VILA GUILHERME,41501.941176,32.588235,5508.294118,651.491765,0.000000,0.000000,1585.294706,0.235294
LAPA,49225.923077,32.769231,6124.800000,651.207692,3753.370000,2012.075385,981.466923,0.230769
BUTANTA,61442.318182,31.590909,7053.636364,713.445909,797.132727,371.774545,2065.406818,0.227273
JABAQUARA,69099.333333,32.888889,6162.077778,519.224444,0.000000,0.000000,2164.093333,0.222222
FREGUESIA-BRASILANDIA,51818.750000,31.200000,5436.500000,692.797500,0.000000,0.000000,1830.567000,0.200000
SANTANA-TUCURUVI,59414.272727,30.272727,5350.454545,540.743636,12871.037273,9294.137273,187.093636,0.181818
JACANA-TREMEMBE,49051.615385,32.076923,4445.107692,769.080769,0.000000,0.000000,1497.866154,0.153846
VILA MARIANA,55028.842105,32.894737,7893.863158,889.390526,10708.370526,6934.871053,661.510000,0.105263
SANTO AMARO,51157.363636,32.181818,6169.500000,636.152727,9020.133636,6520.041818,345.461818,0.090909
MOOCA,54845.615385,31.230769,6635.384615,733.460000,9794.209231,5985.428462,255.160769,0.076923
PINHEIROS,56449.076923,36.615385,12676.096154,810.690000,16168.524615,11076.213846,0.000000,0.076923

In [ ]:
# Exclui a coluna Cliente

dados.drop('Cliente', axis=1).groupby(by='Distrito').mean(numeric_only=True)

,Idade,Salario,Saldo_cc,Saldo_poupança,Saldo_investimento,Devedor_cartao,Inadimplente
Distrito,,,,,,,
ARICANDUVA-FORMOSA-CARRAO,31.416667,5477.666667,395.705000,0.000000,0.000000,1234.876667,0.416667
BUTANTA,31.590909,7053.636364,713.445909,797.132727,371.774545,2065.406818,0.227273
CAMPO LIMPO,32.130435,5462.652174,691.462609,0.000000,0.000000,2716.144348,0.304348
CAPELA DO SOCORRO,32.052632,3871.957895,432.477895,0.000000,0.000000,2180.389474,0.421053
CASA VERDE-CACHOEIRINHA,32.176471,6900.220588,730.812941,0.000000,0.000000,1960.548235,0.294118
CIDADE ADEMAR,33.333333,4628.200000,655.425000,0.000000,0.000000,2720.068333,0.416667
CIDADE TIRADENTES,31.571429,4413.942857,553.777143,0.000000,0.000000,2083.540000,0.285714
ERMELINO MATARAZZO,30.888889,5459.666667,459.871111,1832.421111,1040.307778,1709.377778,0.444444
FREGUESIA-BRASILANDIA,31.200000,5436.500000,692.797500,0.000000,0.000000,1830.567000,0.200000
GUAIANASES,33.333333,4550.400000,792.953333,0.000000,0.000000,1839.290000,0.500000
IPIRANGA,32.285714,7077.942857,707.821429,1474.380000,1088.118571,1357.560000,0.285714
ITAIM PAULISTA,32.600000,5683.700000,711.321500,0.000000,0.000000,2192.458000,0.350000
ITAQUERA,32.653846,3899.296154,697.180769,0.000000,0.000000,2944.003846,0.461538
JABAQUARA,32.888889,6162.077778,519.224444,0.000000,0.000000,2164.093333,0.222222
JACANA-TREMEMBE,32.076923,4445.107692,769.080769,0.000000,0.000000,1497.866154,0.153846
LAPA,32.769231,6124.800000,651.207692,3753.370000,2012.075385,981.466923,0.230769
M'BOI MIRIM,32.095238,3743.411905,725.521905,0.000000,0.000000,1879.669548,0.380952
MOOCA,31.230769,6635.384615,733.460000,9794.209231,5985.428462,255.160769,0.076923
PARELHEIROS,30.266667,3711.680000,681.799333,0.000000,0.000000,1443.010000,0.466667
PENHA,31.450000,5490.750000,638.500000,0.000000,0.000000,1927.856500,0.400000
PERUS,30.500000,5244.000000,731.075000,0.000000,0.000000,1804.671667,0.333333
PINHEIROS,36.615385,12676.096154,810.690000,16168.524615,11076.213846,0.000000,0.076923
PIRITUBA-JARAGUA,31.523810,5836.857143,709.225714,0.000000,0.000000,1815.450476,0.238095
SANTANA-TUCURUVI,30.272727,5350.454545,540.743636,12871.037273,9294.137273,187.093636,0.181818
SANTO AMARO,32.181818,6169.500000,636.152727,9020.133636,6520.041818,345.461818,0.090909
SAO MATEUS,31.450000,3828.370000,521.920500,0.000000,0.000000,1555.744000,0.350000
SAO MIGUEL,33.062500,4007.893750,821.531875,0.000000,0.000000,1647.735000,0.312500
SAPOPEMBA,33.625000,5792.687500,705.633125,0.000000,0.000000,2528.639375,0.250000
SE,31.571429,7476.866667,633.226667,756.222857,605.809524,988.514286,0.333333
VILA MARIA-VILA GUILHERME,32.588235,5508.294118,651.491765,0.000000,0.000000,1585.294706,0.235294
VILA MARIANA,32.894737,7893.863158,889.390526,10708.370526,6934.871053,661.510000,0.105263
VILA PRUDENTE,31.090909,5893.200000,232.494545,1476.780909,1111.703636,889.233636,0.454545

## Subconjuntos lógicos de dados: loc

In [ ]:
dados.loc[dados['Distrito']=='JABAQUARA']

,Cliente,Sexo,Idade,Empresa,Salario,Saldo_cc,Saldo_poupança,Saldo_investimento,Devedor_cartao,Inadimplente,Distrito
34,7994,M,31,Privada,6079.7,642.11,0.0,0.0,1273.00,0,JABAQUARA
166,34453,M,31,Pública,5826.7,1207.69,0.0,0.0,2089.53,0,JABAQUARA
329,65131,F,33,Privada,6024.7,-69.54,0.0,0.0,2842.09,1,JABAQUARA
348,68209,F,30,Privada,5727.7,326.47,0.0,0.0,2166.79,0,JABAQUARA
418,85715,M,36,Autônomo,6922.3,1072.22,0.0,0.0,2049.04,0,JABAQUARA
419,86028,M,35,Privada,6149.0,853.75,0.0,0.0,435.00,0,JABAQUARA
452,90485,F,32,Privada,6088.5,785.52,0.0,0.0,2617.15,0,JABAQUARA
454,90971,M,34,Privada,6265.6,-63.46,0.0,0.0,2988.43,0,JABAQUARA
467,92908,M,34,Privada,6374.5,-81.74,0.0,0.0,3015.81,1,JABAQUARA

In [ ]:
dados.loc[((dados['Distrito']=='JABAQUARA') | (dados['Distrito']=='MOOCA')) & (dados['Sexo']=='M')]

,Cliente,Sexo,Idade,Empresa,Salario,Saldo_cc,Saldo_poupança,Saldo_investimento,Devedor_cartao,Inadimplente,Distrito
34,7994,M,31,Privada,6079.70,642.11,0.00,0.00,1273.00,0,JABAQUARA
108,22166,M,34,Autônomo,7025.00,744.80,17175.54,10559.79,0.00,0,MOOCA
146,31744,M,34,Pública,6980.00,892.44,17357.12,7758.28,0.00,0,MOOCA
166,34453,M,31,Pública,5826.70,1207.69,0.00,0.00,2089.53,0,JABAQUARA
208,42732,M,29,Pública,6681.25,1080.10,16183.62,10242.06,0.00,0,MOOCA
220,44870,M,34,Pública,6696.25,818.62,0.00,0.00,0.00,0,MOOCA
373,76296,M,31,Privada,7346.25,776.56,0.00,0.00,1183.72,0,MOOCA
418,85715,M,36,Autônomo,6922.30,1072.22,0.00,0.00,2049.04,0,JABAQUARA
419,86028,M,35,Privada,6149.00,853.75,0.00,0.00,435.00,0,JABAQUARA
454,90971,M,34,Privada,6265.60,-63.46,0.00,0.00,2988.43,0,JABAQUARA
467,92908,M,34,Privada,6374.50,-81.74,0.00,0.00,3015.81,1,JABAQUARA

In [ ]:
dados.loc[dados['Distrito'].isin(['JABAQUARA','MOOCA']) & (dados['Sexo']=='F')]

,Cliente,Sexo,Idade,Empresa,Salario,Saldo_cc,Saldo_poupança,Saldo_investimento,Devedor_cartao,Inadimplente,Distrito
51,11028,F,28,Pública,6447.50,1188.81,15632.34,10260.99,0.00,0,MOOCA
188,38275,F,30,Privada,6317.50,-137.85,0.00,0.00,1025.63,1,MOOCA
212,43567,F,33,Autônomo,5957.50,350.03,14143.06,9245.37,0.00,0,MOOCA
278,55845,F,29,Pública,6501.25,678.85,0.00,0.00,1107.74,0,MOOCA
329,65131,F,33,Privada,6024.70,-69.54,0.00,0.00,2842.09,1,JABAQUARA
348,68209,F,30,Privada,5727.70,326.47,0.00,0.00,2166.79,0,JABAQUARA
388,79111,F,28,Privada,6682.50,859.24,16175.37,8272.56,0.00,0,MOOCA
421,86575,F,32,Privada,6952.50,734.82,16480.15,11897.19,0.00,0,MOOCA
425,86975,F,30,Privada,6766.25,734.53,0.00,0.00,0.00,0,MOOCA
452,90485,F,32,Privada,6088.50,785.52,0.00,0.00,2617.15,0,JABAQUARA
470,93809,F,34,Autônomo,5906.25,814.03,14177.52,9574.33,0.00,0,MOOCA

In [ ]:
dados.loc[dados['Idade']>40]

,Cliente,Sexo,Idade,Empresa,Salario,Saldo_cc,Saldo_poupança,Saldo_investimento,Devedor_cartao,Inadimplente,Distrito
97,20702,M,47,Privada,8915.00,1838.56,0.00,0.00,3957.62,0,SAPOPEMBA
129,27405,F,44,Autônomo,5324.20,1788.25,0.00,0.00,3444.63,1,SAO MIGUEL
181,37588,M,45,Privada,17139.00,1080.14,17173.34,11328.52,0.00,0,PINHEIROS
318,63125,M,41,Privada,4458.35,1168.78,0.00,0.00,464.00,0,M'BOI MIRIM
440,89226,M,41,Privada,12919.50,643.46,17153.27,11864.85,0.00,0,PINHEIROS

In [ ]:
dados.loc[~(dados['Idade']<=40)]

,Cliente,Sexo,Idade,Empresa,Salario,Saldo_cc,Saldo_poupança,Saldo_investimento,Devedor_cartao,Inadimplente,Distrito
97,20702,M,47,Privada,8915.00,1838.56,0.00,0.00,3957.62,0,SAPOPEMBA
129,27405,F,44,Autônomo,5324.20,1788.25,0.00,0.00,3444.63,1,SAO MIGUEL
181,37588,M,45,Privada,17139.00,1080.14,17173.34,11328.52,0.00,0,PINHEIROS
318,63125,M,41,Privada,4458.35,1168.78,0.00,0.00,464.00,0,M'BOI MIRIM
440,89226,M,41,Privada,12919.50,643.46,17153.27,11864.85,0.00,0,PINHEIROS

In [ ]:
dados.iloc[0,:]

Cliente                    106
Sexo                         F
Idade                       32
Empresa               Autônomo
Salario                 6162.0
Saldo_cc               -372.36
Saldo_poupança             0.0
Saldo_investimento         0.0
Devedor_cartao         1736.56
Inadimplente                 1
Distrito              IPIRANGA
Name: 0, dtype: object

In [ ]:
dados.iloc[0,1]

'F'

Exercício: Obtenha o salário médio para clientes com mais de 40 anos.

In [ ]:
# Resposta

dados.loc[~(dados['Idade']<=40)]['Salario'].mean()

9751.210000000001